version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  db:
      image: postgres:14-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=hello_django
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django

  redis:
    image: redis:7-alpine

  celery_worker_1:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_celery_worker
    command: /start-celeryworker_1
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  celery_worker_2:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_celery_worker
    command: /start-celeryworker_2
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
      - web

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: